label:  Release
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql:///testdb?useSSL=true
    username: root
    password: 123
  rabbitmq:
    port: 5672
    host: 192.168.3.201
    username: test
    password: test
